# Generated by Django 5.0.6 on 2024-05-26 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="followed_user",
        ),
    ]
