# Generated by Django 5.0.6 on 2024-06-16 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_remove_review_followed_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="tags",
        ),
    ]
