# Generated by Django 5.0.6 on 2024-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("tickets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="reviews", to="tags.tag"
            ),
        ),
    ]
